version: 2.1

jobs:
  build-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Build app
          command: |
            # Your code here
            cd app
            npm install
            npm run build
      - save_cache:
          paths: [app/node_modules]
          key: app-build

  test-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Test app
          command: |
            # Your code here
            cd app
            npm install
            npm run test

  scan-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Scan app
          command: |
            # Your code here
            cd app
            npm install
            npm audit --audit-level=critical

  check-lint-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Scan app
          command: |
            # Your code here
            cd app
            npm install
            npm run lint

workflows:
  default:
    jobs:
      - build-app:
          context: global
      - test-app:
          requires: [build-app]
      - scan-app:
          requires: [build-app]
      - check-lint-app:
          requires: [build-app]
